project:
  title: "MetaDocencia's workshops in numbers"
  render:
    - cursos.qmd



format:
  gfm: 
    output-file: README.md
  html: 
    toc: true
    theme: style.scss

execute: 
  echo: false
  warning: false
